name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'âœ¨ ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ ì¶”ê°€ë˜ì—ˆì–´ìš”'
    labels: ['âœ¨ feat']

  - title: 'ğŸ ë²„ê·¸ê°€ ìˆ˜ì •ë˜ì—ˆì–´ìš”'
    labels: ['ğŸ fix']

  - title: 'ğŸ”¨ ì½”ë“œ ë¦¬íŒ©í„°ë§ì´ ìˆì—ˆì–´ìš”'
    labels: ['ğŸ”¨ refactor']

  - title: 'ğŸ“ƒ ë¬¸ì„œê°€ ë³€ê²½ë˜ì—ˆì–´ìš”'
    labels: ['ğŸ“ƒ docs']

  - title: 'âš™ï¸ ì„¤ì •ì´ë‚˜ ê¸°íƒ€ ì‚¬ì†Œí•œ ì‘ì—…ì´ ìˆì—ˆì–´ìš”'
    labels: ['âš™ï¸ chore']

  - title: 'âœ… í…ŒìŠ¤íŠ¸ê°€ ì¶”ê°€ë˜ì—ˆì–´ìš”'
    labels: ['âœ… test']

  - title: 'ğŸ¨ ìŠ¤íƒ€ì¼ ê´€ë ¨ ìˆ˜ì •ì´ ìˆì—ˆì–´ìš”'
    labels: ['ğŸ¨ style']

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## ğŸš€ ì´ë²ˆ ë²„ì „ì˜ ë³€ê²½ì‚¬í•­
  ---
  $CHANGES

no-changes-template: 'ë³€ê²½ì‚¬í•­ì´ ì—†ì–´ìš” ğŸ‰'

version-resolver:
  major:
    labels: ['1ï¸âƒ£ major']
  minor:
    labels: ['2ï¸âƒ£ minor']
  patch:
    labels: ['3ï¸âƒ£ patch']
  default: patch
