aladin:
  api:
    ttbkey: ${ALADIN_API_KEY}

oauth:
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}
  apple:
    clientId: ${APPLE_CLIENT_ID}
    keyId: ${APPLE_KEY_ID}
    teamId: ${APPLE_TEAM_ID}
    keyPath: ${APPLE_KEY_PATH}
    audience: https://appleid.apple.com
