aladin:
  api:
    ttbkey: ${ALADIN_API_KEY}

oauth:
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}
  apple:
    client-id: ${APPLE_CLIENT_ID}
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    key-path: ${APPLE_KEY_PATH}
    audience: https://appleid.apple.com
