spring:
  cache:
    type: simple

logging:
  aop:
    service:
      enabled: true
      max-log-length: 1000
    controller:
      enabled: true

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  server-name: ${SENTRY_SERVER_NAME}
  traces-sample-rate: 1.0
  send-default-pii: true
  logs:
    enabled: true
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: info

---
spring:
  config:
    activate:
      on-profile: test
  cache:
    type: simple

logging:
  aop:
    service:
      enabled: true
      max-log-length: 500
    controller:
      enabled: true

sentry:
  dsn:
  environment: test
  server-name: reed-test
  traces-sample-rate: 1.0
  send-default-pii: true
  logs:
    enabled: true
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: info
