spring:
  cache:
    type: simple

logging:
  aop:
    service:
      enabled: true
      max-log-length: 1000
    controller:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  cache:
    type: simple

logging:
  aop:
    service:
      enabled: true
      max-log-length: 500
    controller:
      enabled: true
