server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    group:
      dev:
        - persistence
        - jwt
        - redis
        - external
      prod:
        - persistence
        - jwt
        - redis
        - external
      test:
        - persistence
        - jwt
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  override-with-generic-response: false

oauth:
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}
  apple:
    clientId: ${APPLE_CLIENT_ID}
    keyId: ${APPLE_KEY_ID}
    teamId: ${APPLE_TEAM_ID}
    keyPath: ${APPLE_KEY_PATH}
    audience: https://appleid.apple.com

---
spring:
  config:
    import: optional:file:secret/application-dev-secret.properties
    activate:
      on-profile: dev

swagger:
  servers:
    - url: ${SWAGGER_SERVER_URL:http://localhost:8080}
      description: Development Server
  info:
    title: YAPP API (Dev)
    description: YAPP API Documentation for Development
    version: v1.0.0-dev

---
spring:
  config:
    import: optional:file:secret/application-prod-secret.properties
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

---
spring:
  config:
    import: optional:file:../secret/application-test-secret.properties
    activate:
      on-profile: test

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
