jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 1800      # 30 minutes (초 단위)
  refresh-token-expiration: 1209600  # 2 weeks (초 단위)

---
spring:
  config:
    activate:
      on-profile: test

jwt:
  secret-key: this-is-a-simple-key-for-testing-purpose-only
  access-token-expiration: 120        # 2 minute (초 단위, 테스트용 짧게 설정)
  refresh-token-expiration: 3600      # 1 hour (초 단위, 테스트용 짧게 설정)
