server:
  port: 8080
  shutdown: graceful

spring:
  jackson:
    time-zone: Asia/Seoul
  profiles:
    group:
      dev:
        - persistence
        - jwt
        - redis
      prod:
        - persistence
        - jwt
        - redis
      test:
        - persistence
        - jwt
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

---
spring:
  config:
    import: optional:file:secret/application-dev-secret.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import: optional:file:secret/application-prod-secret.properties
    activate:
      on-profile: prod

---
spring:
  config:
    import: optional:file:../secret/application-test-secret.properties
    activate:
      on-profile: test
