server:
  port: 8082
  shutdown: graceful

spring:
  jackson:
    time-zone: Asia/Seoul
  profiles:
    group:
      dev:
        - persistence
        - crosscutting
        - redis
        - external
        - observability
      prod:
        - persistence
        - crosscutting
        - redis
        - external
        - observability
      test:
        - persistence
        - crosscutting
        - redis
        - external
        - observability
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

app:
  module-name: batch

---
spring:
  config:
    import: optional:file:secret/application-dev-secret.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import: optional:file:secret/application-prod-secret.properties
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: test
